In [7]:
import cv2

In [8]:
import numpy as np

In [9]:
x =np.array([[1,2,3],[4,5,6]])

In [10]:
x[0][:2]

array([1, 2])

In [11]:
data = cv2.imread('../images/1117/good.jpg')
data.shape

(853, 480, 3)

In [12]:
cv2.imwrite('../images/1117/goodR.jpg',data[:,:,0])
cv2.imwrite('../images/1117/goodG.jpg',data[:,:,1])
cv2.imwrite('../images/1117/goodB.jpg',data[:,:,2])

True

In [13]:
print(data[:][:][1])
print(data[0])

[[199 219 230]
 [198 218 229]
 [198 218 229]
 ...
 [156 176 187]
 [155 175 186]
 [155 175 186]]
[[198 218 229]
 [198 218 229]
 [197 217 228]
 ...
 [156 176 187]
 [156 176 187]
 [155 175 186]]


In [15]:
data = cv2.imread('../images/1117/good.jpg')
copied = data.copy()
copied[:,:,1]=0
copied[:,:,2]=0
cv2.imwrite('../images/1117/goodB.jpg',copied)

True

In [16]:
data = cv2.imread('../images/1117/good.jpg')
copied = data.copy()
x = copied.shape[0]
y = copied.shape[1]
x_up = round(x/2)
y_up = round(y/2)

copied = data.copy()
copied[x_up:,y_up:,0]=0
# copied[x_up:,y_up:,1]=0
copied[x_up:,y_up:,2]=0
cv2.imwrite('../images/1117/BBBB.jpg',copied)

True

In [23]:
print(round(1.5))
print(5//2)
print(5/2)
print(int(5/2))
print(round(5/2))

2
2
2.5
2
2


In [24]:
data = cv2.imread('../images/1117/good.jpg')
copied3 = data.copy()
x = copied3.shape[0]
y = copied3.shape[1]


x_up = round(x/2)
y_up = round(y/2)

copied3[:,:,0] = 255
copied3[:,:,1] = 255
copied3[:,:,2] = 255

cv2.imwrite('../images/1117/zzz.jpg',copied3)

True

In [25]:
data = cv2.imread('../images/1117/good.jpg')
copied3 = data.copy()
x = copied3.shape[0]
y = copied3.shape[1]


x_up = round(x/2)
y_up = round(y/2)

# 왼쪽 위
copied3[:x_up,:y_up,0] = 0
copied3[:x_up,:y_up,1] = 0
copied3[:x_up,:y_up,2] = 0

# 오른쪽 위
copied3[:x_up,y_up:,0] = 100
copied3[:x_up,y_up:,1] = 100
copied3[:x_up,y_up:,2] = 100

# 왼쪽 밑
copied3[x_up:x,:y,0] = 200
copied3[x_up:x,:y,1] = 200
copied3[x_up:x,:y,2] = 200

# 오른쪽 밑
copied3[x_up:,y_up:,0] = 255
copied3[x_up:,y_up:,1] = 255
copied3[x_up:,y_up:,2] = 255

cv2.imwrite('../images/1117/zzz.jpg',copied3)

True

In [26]:
data = cv2.imread('../images/1117/good.jpg')
copied3 = data.copy()
x = copied3.shape[0]
y = copied3.shape[1]

x_up = round(x/2)
y_up = round(y/2)



# 왼쪽 위 
# :x/2 , 
copied3[:x_up,:y_up,0] = 0
copied3[:x_up,:y_up,1] = 0
copied3[:x_up,:y_up,2] = 0

# 오른쪽 위
# 0:x/2 , y/2:y
copied3[:x_up,y_up:,0] = 100
copied3[:x_up,y_up:,1] = 100
copied3[:x_up,y_up:,2] = 100

# 왼쪽 밑
# x/2: , :
copied3[x_up:,:,0] = 200
copied3[x_up:,:,1] = 200
copied3[x_up:,:,2] = 200

# 오른쪽 밑
copied3[x_up:,y_up:,0] = 255
copied3[x_up:,y_up:,1] = 255
copied3[x_up:,y_up:,2] = 255

cv2.imwrite('../images/1117/zzz.jpg',copied3)

True

In [27]:
# 

# data = cv2.imread('../images/1117/good.jpg')
# copied3 = data.copy()
# x = copied3.shape[0]
# y = copied3.shape[1]

# x_up = x//2
# y_up = y//2

# for i in range(0,x_up):
#     for j in range(x_up,x):
#         for z in range(3):
#             copied3[i,i,z] = 150
#     print("value",(x-j)//255 * 100)

# cv2.imwrite('../images/1117/zzzzz2.jpg',copied3)

value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0
value 0


True

In [ ]:
data = cv2.imread('../images/1117/good.jpg')
copied3 = data.copy()
x = copied3.shape[0]
y = copied3.shape[1]

x_up = x//2
y_up = y//2

for j in range(3):
    interval=0
    for i in range(2):
        interval += x_up
        copied3[x_up:interval, :y_up,j] = 0
        
cv2.imwrite('../images/1117/zzzzz.jpg',copied3)

In [ ]:
data = cv2.imread('../images/1117/good.jpg')
copied3 = data.copy()
x = copied3.shape[0]
y = copied3.shape[1]

x_up = x//2
y_up = y//2

for j in range(3):
    interval=0b
    for i in range(2):
        interval += x_up
        copied3[x_up//2:x_up, :y_up,j] = 0
        
cv2.imwrite('../images/1117/zzzzz.jpg',copied3)

In [ ]:
import cv2
import numpy as np

img = data.copy()   # data = cv2.imread(...) 로 읽은 이미지

H, W, C = img.shape

# 3×2 블록 크기 계산
h_block = H // 3
w_block = W // 2

# 블록별 밝기 scale 값 (0.3 ~ 1.5)
brightness = [
    [0.5, 0.8],   # 1행
    [1.2, 0.4],   # 2행
    [1.5, 0.7]    # 3행
]

# 결과 이미지
out = img.copy()

for i in range(3):      # 3 rows
    for j in range(2):  # 2 cols

        y1 = i * h_block
        y2 = (i + 1) * h_block if i < 2 else H

        x1 = j * w_block
        x2 = (j + 1) * w_block if j < 1 else W

        block = out[y1:y2, x1:x2].astype(np.float32)

        # 밝기 조절
        block = block * brightness[i][j]
        block = np.clip(block, 0, 255).astype(np.uint8)

        # 적용
        out[y1:y2, x1:x2] = block

cv2.imwrite('./images/1117/brightness6_blocks.jpg', out)

In [3]:
import os

# 저장 폴더 생성
temp = '../images/temp'
os.makedirs(temp, exist_ok=True)

In [ ]:
import cv2
import numpy as np


# 원본 이미지 읽기
img = cv2.imread("../images/1117/good.jpg")

# 밝기 배율 10개 (0.3 ~ 1.8 예시)
scales = np.linspace(0.3, 1.8, 10)

for idx, s in enumerate(scales):
    # float32로 변환 후 밝기 조절
    out = img.astype(np.float32) * s
    
    # 값 범위 유지
    out = np.clip(out, 0, 255).astype(np.uint8)
    
    # 파일 이름
    filename = f"{str2}/bright_{idx}.jpg"
    
    # 저장
    cv2.imwrite(filename, out)

print("생성 완료!")

In [5]:
import cv2
import numpy as np
import math

# 이미지 읽기
img = cv2.imread("../images/1117/good.jpg")
H, W, C = img.shape

# 회전 각도 (degree)
theta = 45
rad = math.radians(theta)

# 2×2 회전행렬 (anticlockwise)
R = np.array([
    [ math.cos(rad), -math.sin(rad)],
    [ math.sin(rad),  math.cos(rad)]
])

# 출력 이미지 크기는 기존과 같게 함
out = np.zeros_like(img)

for i in range(5):
    temp = '../images/temp'+str(i)
    # 중심좌표
    cx = W // (i+1)
    cy = H // (i+1)

    for y in range(H):
        for x in range(W):
    
            # (x, y) -> 중심 기준 좌표계로 이동
            xt = x - cx
            yt = y - cy
    
            # 회전행렬 적용
            xr, yr = R @ np.array([yt, xt])
    
            # 다시 원래 좌표계로 이동
            xs = int(round(xr + cx))
            ys = int(round(yr + cy))
    
            # 출력 이미지 범위 체크
            if 0 <= xs < W and 0 <= ys < H:
                out[y, x] = img[ys, xs]
    
    # 저장
    cv2.imwrite(f"{temp}/rotated_manual{i}.jpg", out)

    print("회전 완료!")
    

회전 완료!
회전 완료!
회전 완료!
회전 완료!
회전 완료!


In [52]:
# 원본 이미지 읽기
data = cv2.imread("../images/1117/good.jpg")

In [105]:
# 원본 이미지 읽기
data = cv2.imread("../images/1117/good.jpg")

copied = data.copy()
x = copied.shape[0]
y = copied.shape[1]

# out = np.clip(out, 0, 255).astype(np.uint8)

for v in range(x):
    for u in range(y):
        for z in range(3):
            # print(v,u,z)
            copied[v,u,z] = np.clip(v*u*z%255,0,255).astype(np.uint8)

cv2.imwrite("../images/test.jpg", copied)
    

True